data_config_bios:
    train_pkl: "/share/cp/datasets/nlp/text_classification_bias/bios/only_task_balanced/train_balanced_every_job.pkl"
    val_pkl: "/share/cp/datasets/nlp/text_classification_bias/bios/only_task_balanced/val.pkl"
    test_pkl: "/share/cp/datasets/nlp/text_classification_bias/bios/only_task_balanced/test.pkl"
    labels_protected_path: "/share/cp/datasets/nlp/text_classification_bias/bios/labels_protected_gender.txt"
    labels_task_path: "/share/cp/datasets/nlp/text_classification_bias/bios/labels_task.txt"
    output_dir: "checkpoints_bios"
    log_dir: "logs_bios"
data_config_pan16:
    train_pkl: "/share/cp/datasets/nlp/text_classification_bias/PAN16_prep/train_balanced_every_age.pkl"
    val_pkl: "/share/cp/datasets/nlp/text_classification_bias/PAN16_prep/test.pkl"
    test_pkl: "/share/cp/datasets/nlp/text_classification_bias/PAN16_prep/test.pkl"
    labels_protected_path: "/share/cp/datasets/nlp/text_classification_bias/PAN16_prep/labels_protected_gender.txt"
    labels_task_path: "/share/cp/datasets/nlp/text_classification_bias/PAN16_prep/labels_task.txt"
    output_dir: "checkpoints_pan16"
    log_dir: "logs_pan16"
data_config_hatespeech:
    train_pkl: "/share/cp/datasets/nlp/hate_speech/Twitter/AAEpredicted/pickle_format/train.pkl"
    val_pkl: "/share/cp/datasets/nlp/hate_speech/Twitter/AAEpredicted/pickle_format/val.pkl"
    test_pkl: "/share/cp/datasets/nlp/hate_speech/Twitter/AAEpredicted/pickle_format/test.pkl"
    labels_protected_path: "/share/cp/datasets/nlp/hate_speech/Twitter/AAEpredicted/pickle_format/labels_protected_race.txt"
    labels_task_path: "/share/cp/datasets/nlp/hate_speech/Twitter/AAEpredicted/pickle_format/labels_task.txt"
    output_dir: "checkpoints_hatespeech"
    log_dir: "logs_hatespeech"
model_config:
    model_name: "google/bert_uncased_L-4_H-256_A-4" # "bert-base-uncased" # "google/bert_uncased_L-4_H-256_A-4" # "google/bert_uncased_L-2_H-128_A-2"
    batch_size: 64
train_config_diff_pruning:
    bottleneck: False
    structured_diff_pruning: True
    alpha_init: 5
    concrete_samples: 1
    concrete_lower: -1.5
    concrete_upper: 1.5
    num_epochs_warmup: 0
    num_epochs_finetune: 15
    num_epochs_fixmask: 15
    weight_decay: 0.0
    learning_rate: 2e-5
    learning_rate_bottleneck: 1e-4
    learning_rate_task_head: 1e-4
    learning_rate_adv_head: 1e-4
    learning_rate_alpha: 0.1
    task_dropout: .3
    task_n_hidden: 0
    adv_dropout: .3
    adv_n_hidden: 1
    adv_count: 5
    adv_lambda: 1.
    bottleneck_dim: 16
    bottleneck_dropout: .3
    optimizer_warmup_steps: 0
    sparsity_pen: 1.25e-7
    max_grad_norm: 1.0
    fixmask_pct: 0.1
    logging_step: 5
    cooldown: 5
train_config_baseline:
    bottleneck: False
    num_epochs_warmup: 0
    num_epochs: 20
    learning_rate: 2e-5
    learning_rate_bottleneck: 1e-4
    learning_rate_task_head: 1e-4
    learning_rate_adv_head: 1e-4
    task_dropout: .3
    task_n_hidden: 0
    adv_dropout: .3
    adv_n_hidden: 1
    adv_count: 5
    adv_lambda: 1.
    bottleneck_dim: 16
    bottleneck_dropout: .3
    optimizer_warmup_steps: 0
    max_grad_norm: 1.0
    logging_step: 5
    cooldown: 5
adv_attack:
    num_epochs: 100
    learning_rate: 1e-4
    adv_n_hidden: 1
    adv_count: 5
    adv_dropout: .3
    logging_step: 5
    cooldown: 5


